version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Asia/Tokyo
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
    - 4.2.3
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: "@types/express"
    versions:
    - 4.17.9
